#!/bin/bash
echo "write a phrase"
read phrase
num_words=$(echo "$phrase" | wc -w)
num_space=$(echo "$phrase" | tr -cd ' ' | wc -c)
echo "this is the number of words $num_words"
echo "this is the number of spaces $num_space"
